services:
  back:
    image: inksne/tr-back-image:latest
    container_name: back-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    env_file:
      - ./.env
    command: ["python", "main.py"]
    restart: always